### ISSUE TITLE
bugs in timers without activity

### ISSUE THREAD

**Issue by startupleo2013** [jbuchbinder/statsd-ganglia-backend#4]
rwhen no activities for timer metrics, it tries to keep sending min/max to avoid ganglia expiry, however, min/max etc was undefined due to variable scope, so are the keys (say stats_timers_key_mean_undefined, which should be stats_timers_key_mean_90).

Also, in most cases, we should reset all timers without any activities to 0, rather than the last value we get.

**Comment by startupleo2013** [comment]
I haven't tested out, but in "var clean_pct = '' + pct;", the pct is undefined right? Shouldn't a for loop be used to reset all Nth percentile values?

**Comment by atdt** [comment]
startupleo2013 is correct; this is still a bug.
